# -*- coding: utf-8 -*-
"""The Area Of Triangle.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Br98PWm7x_im7UScqwFD4_ay7XitLArh
"""

# Write a program that calculates the area of a triangle using the formula A = (b * h) / 2.

base=float(input("Enter The Base Of The Triangle"))
height=float(input("Enter The Height Of The Triangle"))
AreaOfTriangle=(base*height)/2
print("The Area Of Triangle Is",AreaOfTriangle)