# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOpYuNiqwOnTuPy5EojRP0LR1IDoiI_D
"""

# Write a program that prompts the user to enter two floating-point numbers and then calculate their average.

Num1= float(input("Enter the first floating-point number"))

Num2= float(input("Enter the second floating-point number"))

Average=(Num1+Num2)/2

print("The Average Of Two Numbers Are", Average)